### ISSUE TITLE
Error while running the **tukey_function.R**  script

### ISSUE THREAD

**Issue by sanjaysingh765** [vicruiser/tukey_test_plot#1]
Hi I am getting following error when using the **tukey_function.R**  script

> data <- read.csv("data", header=T, sep=",")
>   significance<-tukey.plot.significance(data) 
Using X as id variables
Error in levels(tukey_groups[[i]]$groups$trt) <- rownames(tukey_groups[[i]]$means) : 
  attempt to set an attribute on NULL

Can you look into that please? I used the data you provided as an example. Thanks.

**Comment by karnayogendra** [comment]
Hi I got the same problem as sanjaysingh765 found so would you please solve it. It's pretty useful for me but can't run through.
Regards,
Yogendra

**Comment by mBerlow** [comment]
I'm also getting the same error when attempting to use the `tukey.plot.significance()` function on the example data: 
`Error during wrapup: attempt to set an attribute on NULL`

Would love an answer! 
Thank you,
Mae

**Comment by vicruiser** [comment]
Ok guys, I'm sorry for the delay. I obviously don't need this function anymore. I think the issues were due to R packages updates. I've reworked the entire script (my programming skills improved a bit after 3 years...) and the current function is way shorter. Hope it works now! If there are any other issues I'll be happy to help!. 

Cheers! 
Vicky.
